"""
Retry monitoring and observability system for comprehensive tracking of retry operations.

This module provides detailed monitoring, metrics collection, and alerting capabilities
for retry operations, circuit breakers, and failure patterns.
"""

import logging
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any

log = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class RetryEvent:
    """A single retry event for tracking and analysis."""

    timestamp: datetime
    operation_name: str
    attempt_number: int
    success: bool
    error_category: str
    error_message: str
    delay: float
    duration: float
    circuit_breaker_state: str = "unknown"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "operation_name": self.operation_name,
            "attempt_number": self.attempt_number,
            "success": self.success,
            "error_category": self.error_category,
            "error_message": self.error_message,
            "delay": self.delay,
            "duration": self.duration,
            "circuit_breaker_state": self.circuit_breaker_state,
        }


@dataclass
class OperationMetrics:
    """Comprehensive metrics for a specific operation."""

    operation_name: str
    total_calls: int = 0
    successful_calls: int = 0
    failed_calls: int = 0
    retries_triggered: int = 0
    circuit_breaker_opens: int = 0

    # Timing metrics
    total_duration: float = 0.0
    min_duration: float = float("inf")
    max_duration: float = 0.0

    # Retry delay metrics
    total_delay: float = 0.0
    min_delay: float = float("inf")
    max_delay: float = 0.0

    # Error tracking
    error_counts: defaultdict[str, int] = field(
        default_factory=lambda: defaultdict(int)
    )

    # Recent events for detailed analysis
    recent_events: list[RetryEvent] = field(default_factory=list)

    @property
    def success_rate(self) -> float:
        """Calculate success rate percentage."""
        if self.total_calls == 0:
            return 0.0
        return (self.successful_calls / self.total_calls) * 100.0

    @property
    def failure_rate(self) -> float:
        """Calculate failure rate percentage."""
        return 100.0 - self.success_rate

    @property
    def average_duration(self) -> float:
        """Calculate average operation duration."""
        if self.total_calls == 0:
            return 0.0
        return self.total_duration / self.total_calls

    @property
    def average_delay(self) -> float:
        """Calculate average retry delay."""
        if self.retries_triggered == 0:
            return 0.0
        return self.total_delay / self.retries_triggered

    def add_event(self, event: RetryEvent, max_recent_events: int = 100) -> None:
        """Add an event and update metrics."""
        self.total_calls += 1

        if event.success:
            self.successful_calls += 1
        else:
            self.failed_calls += 1
            self.error_counts[event.error_category] += 1

        if event.attempt_number > 1:
            self.retries_triggered += 1
            self.total_delay += event.delay
            self.min_delay = min(self.min_delay, event.delay)
            self.max_delay = max(self.max_delay, event.delay)

        if event.circuit_breaker_state == "open":
            self.circuit_breaker_opens += 1

        # Update duration metrics
        self.total_duration += event.duration
        if event.duration > 0:
            self.min_duration = min(self.min_duration, event.duration)
            self.max_duration = max(self.max_duration, event.duration)

        # Keep recent events for detailed analysis
        self.recent_events.append(event)
        if len(self.recent_events) > max_recent_events:
            self.recent_events.pop(0)


@dataclass
class Alert:
    """An alert generated by the monitoring system."""

    timestamp: datetime
    severity: AlertSeverity
    operation_name: str
    message: str
    details: dict[str, Any]
    resolved: bool = False
    resolved_at: datetime | None = None

    def resolve(self) -> None:
        """Mark alert as resolved."""
        self.resolved = True
        self.resolved_at = datetime.utcnow()

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "severity": self.severity.value,
            "operation_name": self.operation_name,
            "message": self.message,
            "details": self.details,
            "resolved": self.resolved,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
        }


class RetryMonitor:
    """
    Comprehensive monitoring and observability system for retry operations.

    Tracks all retry operations, generates alerts, and provides detailed metrics
    for operational visibility and debugging.
    """

    def __init__(
        self,
        max_recent_events: int = 100,
        alert_thresholds: dict[str, Any] | None = None,
    ):
        self.max_recent_events = max_recent_events
        self.operations: dict[str, OperationMetrics] = {}
        self.alerts: list[Alert] = []

        # Default alert thresholds
        self.alert_thresholds = {
            "failure_rate_high": 50.0,  # High failure rate threshold (%)
            "failure_rate_critical": 80.0,  # Critical failure rate threshold (%)
            "circuit_breaker_opens_medium": 3,  # Medium alert for circuit breaker opens
            "circuit_breaker_opens_high": 5,  # High alert for circuit breaker opens
            "consecutive_failures_medium": 5,  # Medium alert for consecutive failures
            "consecutive_failures_high": 10,  # High alert for consecutive failures
            "average_delay_high": 10.0,  # High average retry delay (seconds)
            "max_delay_critical": 60.0,  # Critical max retry delay (seconds)
            "time_window_minutes": 15,  # Time window for rate calculations
        }

        if alert_thresholds:
            self.alert_thresholds.update(alert_thresholds)

    def record_event(
        self,
        operation_name: str,
        attempt_number: int,
        success: bool,
        error_category: str = "",
        error_message: str = "",
        delay: float = 0.0,
        duration: float = 0.0,
        circuit_breaker_state: str = "unknown",
    ) -> None:
        """Record a retry event and update metrics."""
        event = RetryEvent(
            timestamp=datetime.utcnow(),
            operation_name=operation_name,
            attempt_number=attempt_number,
            success=success,
            error_category=error_category,
            error_message=error_message,
            delay=delay,
            duration=duration,
            circuit_breaker_state=circuit_breaker_state,
        )

        # Initialize operation metrics if not exists
        if operation_name not in self.operations:
            self.operations[operation_name] = OperationMetrics(operation_name)

        # Add event to operation metrics
        self.operations[operation_name].add_event(event, self.max_recent_events)

        # Check for alert conditions
        self._check_alerts(operation_name, event)

        # Log detailed event for debugging
        if success:
            if attempt_number > 1:
                log.info(
                    f"Operation '{operation_name}' succeeded after {attempt_number} attempts "
                    f"(total delay: {delay:.2f}s, duration: {duration:.2f}s)"
                )
        else:
            log.warning(
                f"Operation '{operation_name}' failed on attempt {attempt_number}: "
                f"{error_category} - {error_message} "
                f"(delay: {delay:.2f}s, duration: {duration:.2f}s, circuit: {circuit_breaker_state})"
            )

    def _check_alerts(self, operation_name: str, event: RetryEvent) -> None:
        """Check if any alert conditions are met and generate alerts."""
        metrics = self.operations[operation_name]

        # Check failure rate alerts (only if we have enough samples)
        if metrics.total_calls >= 5:
            failure_rate = metrics.failure_rate

            if failure_rate >= self.alert_thresholds["failure_rate_critical"]:
                self._generate_alert(
                    AlertSeverity.CRITICAL,
                    operation_name,
                    f"Critical failure rate: {failure_rate:.1f}%",
                    {
                        "failure_rate": failure_rate,
                        "total_calls": metrics.total_calls,
                        "failed_calls": metrics.failed_calls,
                        "time_window": "current session",
                    },
                )
            elif failure_rate >= self.alert_thresholds["failure_rate_high"]:
                self._generate_alert(
                    AlertSeverity.HIGH,
                    operation_name,
                    f"High failure rate: {failure_rate:.1f}%",
                    {
                        "failure_rate": failure_rate,
                        "total_calls": metrics.total_calls,
                        "failed_calls": metrics.failed_calls,
                        "time_window": "current session",
                    },
                )

        # Check circuit breaker open alerts
        if event.circuit_breaker_state == "open":
            if (
                metrics.circuit_breaker_opens
                >= self.alert_thresholds["circuit_breaker_opens_high"]
            ):
                self._generate_alert(
                    AlertSeverity.HIGH,
                    operation_name,
                    f"Circuit breaker opened {metrics.circuit_breaker_opens} times",
                    {
                        "circuit_breaker_opens": metrics.circuit_breaker_opens,
                        "current_state": "open",
                        "recent_errors": [
                            e.error_category
                            for e in metrics.recent_events[-5:]
                            if not e.success
                        ],
                    },
                )
            elif (
                metrics.circuit_breaker_opens
                >= self.alert_thresholds["circuit_breaker_opens_medium"]
            ):
                self._generate_alert(
                    AlertSeverity.MEDIUM,
                    operation_name,
                    f"Circuit breaker instability detected ({metrics.circuit_breaker_opens} opens)",
                    {
                        "circuit_breaker_opens": metrics.circuit_breaker_opens,
                        "current_state": "open",
                    },
                )

        # Check consecutive failures
        consecutive_failures = self._count_consecutive_failures(metrics.recent_events)
        if consecutive_failures >= self.alert_thresholds["consecutive_failures_high"]:
            self._generate_alert(
                AlertSeverity.HIGH,
                operation_name,
                f"High consecutive failures: {consecutive_failures}",
                {
                    "consecutive_failures": consecutive_failures,
                    "recent_error_types": [
                        e.error_category
                        for e in metrics.recent_events[-consecutive_failures:]
                    ],
                },
            )
        elif (
            consecutive_failures >= self.alert_thresholds["consecutive_failures_medium"]
        ):
            self._generate_alert(
                AlertSeverity.MEDIUM,
                operation_name,
                f"Multiple consecutive failures: {consecutive_failures}",
                {
                    "consecutive_failures": consecutive_failures,
                    "recent_error_types": [
                        e.error_category
                        for e in metrics.recent_events[-consecutive_failures:]
                    ],
                },
            )

        # Check retry delay alerts
        if metrics.retries_triggered > 0:
            avg_delay = metrics.average_delay
            max_delay = metrics.max_delay

            if max_delay >= self.alert_thresholds["max_delay_critical"]:
                self._generate_alert(
                    AlertSeverity.CRITICAL,
                    operation_name,
                    f"Critical retry delay: {max_delay:.2f}s max",
                    {
                        "max_delay": max_delay,
                        "average_delay": avg_delay,
                        "retries_triggered": metrics.retries_triggered,
                    },
                )
            elif avg_delay >= self.alert_thresholds["average_delay_high"]:
                self._generate_alert(
                    AlertSeverity.HIGH,
                    operation_name,
                    f"High average retry delay: {avg_delay:.2f}s",
                    {
                        "average_delay": avg_delay,
                        "max_delay": max_delay,
                        "retries_triggered": metrics.retries_triggered,
                    },
                )

    def _count_consecutive_failures(self, events: list[RetryEvent]) -> int:
        """Count consecutive failures from the end of the event list."""
        consecutive = 0
        for event in reversed(events):
            if not event.success:
                consecutive += 1
            else:
                break
        return consecutive

    def _generate_alert(
        self,
        severity: AlertSeverity,
        operation_name: str,
        message: str,
        details: dict[str, Any],
    ) -> None:
        """Generate an alert and add it to the alerts list."""
        # Check if similar alert already exists and is unresolved
        similar_alert = None
        for alert in reversed(self.alerts):
            if (
                alert.operation_name == operation_name
                and alert.severity == severity
                and not alert.resolved
                and abs((datetime.utcnow() - alert.timestamp).total_seconds()) < 300
            ):  # 5 minutes
                similar_alert = alert
                break

        if similar_alert:
            # Update existing alert details
            similar_alert.details.update(details)
            log.debug(f"Updated existing {severity.value} alert for {operation_name}")
        else:
            # Create new alert
            alert = Alert(
                timestamp=datetime.utcnow(),
                severity=severity,
                operation_name=operation_name,
                message=message,
                details=details,
            )

            self.alerts.append(alert)

            # Log alert based on severity
            log_level = {
                AlertSeverity.LOW: logging.INFO,
                AlertSeverity.MEDIUM: logging.WARNING,
                AlertSeverity.HIGH: logging.WARNING,
                AlertSeverity.CRITICAL: logging.ERROR,
            }

            log.log(
                log_level[severity],
                f"RETRY ALERT [{severity.value.upper()}] {operation_name}: {message}",
            )

    def get_operation_metrics(self, operation_name: str) -> OperationMetrics | None:
        """Get metrics for a specific operation."""
        return self.operations.get(operation_name)

    def get_all_metrics(self) -> dict[str, dict[str, Any]]:
        """Get metrics for all operations."""
        result = {}
        for name, metrics in self.operations.items():
            result[name] = {
                "operation_name": metrics.operation_name,
                "total_calls": metrics.total_calls,
                "successful_calls": metrics.successful_calls,
                "failed_calls": metrics.failed_calls,
                "success_rate": metrics.success_rate,
                "failure_rate": metrics.failure_rate,
                "retries_triggered": metrics.retries_triggered,
                "circuit_breaker_opens": metrics.circuit_breaker_opens,
                "average_duration": metrics.average_duration,
                "min_duration": (
                    metrics.min_duration
                    if metrics.min_duration != float("inf")
                    else 0.0
                ),
                "max_duration": metrics.max_duration,
                "average_delay": metrics.average_delay,
                "min_delay": (
                    metrics.min_delay if metrics.min_delay != float("inf") else 0.0
                ),
                "max_delay": metrics.max_delay,
                "error_counts": dict(metrics.error_counts),
                "recent_events_count": len(metrics.recent_events),
            }
        return result

    def get_unresolved_alerts(self) -> list[Alert]:
        """Get all unresolved alerts."""
        return [alert for alert in self.alerts if not alert.resolved]

    def get_recent_alerts(self, minutes: int = 60) -> list[Alert]:
        """Get alerts from the last N minutes."""
        cutoff = datetime.utcnow() - timedelta(minutes=minutes)
        return [alert for alert in self.alerts if alert.timestamp >= cutoff]

    def resolve_alerts_for_operation(self, operation_name: str) -> None:
        """Mark all alerts for an operation as resolved."""
        resolved_count = 0
        for alert in self.alerts:
            if alert.operation_name == operation_name and not alert.resolved:
                alert.resolve()
                resolved_count += 1

        if resolved_count > 0:
            log.info(
                f"Resolved {resolved_count} alerts for operation '{operation_name}'"
            )

    def clear_old_alerts(self, hours: int = 24) -> None:
        """Remove alerts older than specified hours."""
        cutoff = datetime.utcnow() - timedelta(hours=hours)
        original_count = len(self.alerts)
        self.alerts = [alert for alert in self.alerts if alert.timestamp >= cutoff]
        removed_count = original_count - len(self.alerts)

        if removed_count > 0:
            log.info(f"Cleared {removed_count} old alerts (older than {hours} hours)")

    def get_health_summary(self) -> dict[str, Any]:
        """Get overall health summary of retry operations."""
        if not self.operations:
            return {
                "status": "no_operations",
                "message": "No retry operations recorded yet",
                "operations_count": 0,
                "total_calls": 0,
                "overall_success_rate": 0.0,
                "unresolved_alerts": 0,
                "critical_alerts": 0,
            }

        # Aggregate metrics
        total_calls = sum(op.total_calls for op in self.operations.values())
        total_successes = sum(op.successful_calls for op in self.operations.values())
        overall_success_rate = (
            (total_successes / total_calls * 100) if total_calls > 0 else 0.0
        )

        unresolved_alerts = self.get_unresolved_alerts()
        critical_alerts = [
            a for a in unresolved_alerts if a.severity == AlertSeverity.CRITICAL
        ]

        # Determine overall health status
        if critical_alerts:
            status = "critical"
            message = f"System has {len(critical_alerts)} critical alerts"
        elif len(unresolved_alerts) > 5:
            status = "degraded"
            message = f"System has {len(unresolved_alerts)} unresolved alerts"
        elif overall_success_rate < 90.0:
            status = "degraded"
            message = f"Overall success rate is {overall_success_rate:.1f}%"
        else:
            status = "healthy"
            message = "All retry operations are performing well"

        return {
            "status": status,
            "message": message,
            "operations_count": len(self.operations),
            "total_calls": total_calls,
            "overall_success_rate": overall_success_rate,
            "unresolved_alerts": len(unresolved_alerts),
            "critical_alerts": len(critical_alerts),
            "operations": list(self.operations.keys()),
        }


# Global retry monitor instance
retry_monitor = RetryMonitor()
