"""Trading signals and market event types for the InkedUp Polymarket bot.

This module defines the core signal types used throughout the trading system
to communicate trading opportunities, market events, and execution instructions
between strategies, risk management, and order execution components.

Signal Types:
    - TradingSignal: Core trading instruction with market and position details
    - SpreadSignal: Alert for wide bid-ask spreads in markets
    - ComplementSignal: Arbitrage opportunity in binary markets

The signal system provides a standardized interface for:
    - Strategy signal generation and routing
    - Risk validation and position sizing
    - Order generation and execution tracking
    - Performance monitoring and attribution

Example:
    Creating and using trading signals:

    >>> # Basic trading signal
    >>> signal = TradingSignal(
    ...     market_slug="election-2024",
    ...     token_id="0x123...",
    ...     side="buy",
    ...     size=100.0,
    ...     price=0.65,
    ...     strategy="complement_arb"
    ... )
    >>>
    >>> # Spread alert signal
    >>> spread_signal = SpreadSignal(
    ...     market_slug="sports-nfl",
    ...     token_id="0x456...",
    ...     bid=0.45,
    ...     ask=0.65,
    ...     spread_bps=2000  # 20% spread
    ... )
    >>>
    >>> # Complement arbitrage signal
    >>> comp_signal = ComplementSignal(
    ...     market_slug="binary-event",
    ...     yes_token_id="0x789...",
    ...     no_token_id="0xabc...",
    ...     yes_price=0.60,
    ...     no_price=0.45,
    ...     complement_deviation=0.05
    ... )

Signal Flow:
    Strategy -> Signal -> RiskManager -> TradingEngine -> OrderClient

    Signals flow through the system carrying trading intent and market
    context to enable automated decision making and execution.

"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Literal


class SignalAction(str, Enum):
    """Enumeration for trading actions."""

    BUY = "buy"
    SELL = "sell"


class OutcomeType(str, Enum):
    """Enumeration for market outcomes."""

    YES = "yes"
    NO = "no"


@dataclass(slots=True)
class TradingSignal:
    """Unified signal for buy/sell actions emitted by strategies.

    TradingSignal represents a trading instruction generated by a strategy that
    needs to be executed through the risk management and order execution pipeline.
    Enhanced with comprehensive market and outcome tracking for risk management.

    This is the primary signal type used throughout the system for communicating
    trading intent from strategies to the execution engine. It contains all
    necessary information for risk validation, position sizing, and order placement.

    Attributes:
        market_slug: Human-readable market identifier (e.g., "election-2024", "sports-nfl")
        token_id: Blockchain token address for the specific outcome to trade
        side: Trading direction, either "buy" or "sell"
        price: Execution price as a decimal between 0.0 and 1.0 for prediction markets
        size: Position size in USD notional value
        signal_id: Optional unique identifier for tracking and correlation across systems
        outcome_type: Market outcome classification (e.g., "yes", "no") for risk analysis
        created_at: Unix timestamp when the signal was generated

    Examples:
        Basic buy signal for a political prediction market:

        >>> signal = TradingSignal(
        ...     market_slug="election-2024-president",
        ...     token_id="0x123abc456def...",
        ...     side="buy",
        ...     price=0.62,
        ...     size=250.0,
        ...     outcome_type="yes"
        ... )
        >>> print(f"Signal: {signal.side} ${signal.size} at {signal.price}")
        Signal: buy $250.0 at 0.62

        Sell signal with tracking ID:

        >>> import uuid
        >>> signal = TradingSignal(
        ...     market_slug="sports-nfl-superbowl",
        ...     token_id="0x789ghi012jkl...",
        ...     side="sell",
        ...     price=0.45,
        ...     size=100.0,
        ...     signal_id=str(uuid.uuid4()),
        ...     outcome_type="no"
        ... )

    Risk Integration:
        The signal flows through risk validation before execution:

        1. Position size validation against configured limits
        2. Market exposure checks using outcome_type
        3. Price validation against current market conditions
        4. Correlation analysis for portfolio risk management

    Performance Notes:
        - Uses __slots__ for memory efficiency in high-frequency scenarios
        - created_at timestamp enables signal lifecycle tracking
        - signal_id supports distributed tracing and debugging

    """

    market_slug: str
    token_id: str
    side: Literal["buy", "sell"]
    price: float
    size: float
    signal_id: str | None = None  # Optional unique ID for tracking
    outcome_type: str | None = None  # e.g., 'yes', 'no' for risk tracking
    created_at: float = field(default_factory=time.time)


@dataclass(slots=True)
class SpreadSignal:
    """Signal emitted when a wide bid-ask spread condition is detected.

    SpreadSignal alerts the system when a market shows unusually wide spreads
    that may indicate liquidity opportunities, market inefficiencies, or
    potential market making opportunities.

    This signal type is typically generated by market scanning components
    when spread conditions exceed configured thresholds, enabling strategies
    to respond to liquidity gaps or volatility events.

    Attributes:
        market_slug: Human-readable market identifier where spread was detected
        token_id: Specific token/outcome showing the wide spread
        bid: Current best bid price (None if no bids available)
        ask: Current best ask price (None if no asks available)
        spread_bps: Bid-ask spread in basis points (None if cannot calculate)

    Examples:
        Wide spread detected in election market:

        >>> spread_signal = SpreadSignal(
        ...     market_slug="election-2024-swing-state",
        ...     token_id="0x456def789abc...",
        ...     bid=0.42,
        ...     ask=0.68,
        ...     spread_bps=2600  # 26% spread
        ... )
        >>> print(f"Wide spread: {spread_signal.spread_bps} bps")
        Wide spread: 2600 bps

        No liquidity scenario:

        >>> no_liquidity = SpreadSignal(
        ...     market_slug="niche-prediction-market",
        ...     token_id="0x789abc123def...",
        ...     bid=None,  # No buyers
        ...     ask=0.85,
        ...     spread_bps=None  # Cannot calculate
        ... )

    Usage:
        SpreadSignals are typically consumed by:
        - Market making strategies looking for wide spreads
        - Liquidity provision algorithms
        - Risk management systems monitoring market health
        - Performance analytics tracking market efficiency

    Calculation:
        spread_bps = ((ask - bid) / mid_price) * 10000
        where mid_price = (bid + ask) / 2

    """

    market_slug: str
    token_id: str
    bid: float | None
    ask: float | None
    spread_bps: float | None


@dataclass(slots=True)
class ComplementSignal:
    """Signal emitted when complement deviation is detected in binary markets.

    ComplementSignal identifies arbitrage opportunities in binary prediction
    markets where the sum of YES and NO token prices deviates significantly
    from 1.0, creating risk-free profit opportunities through complement trading.

    In efficient binary markets, YES + NO prices should equal ~1.0 (accounting
    for fees and spreads). When this relationship breaks down, it indicates
    market inefficiency that can be exploited through simultaneous positions.

    Attributes:
        market_slug: Human-readable binary market identifier
        yes_token_id: Blockchain address for the YES outcome token
        no_token_id: Blockchain address for the NO outcome token
        yes_price: Current YES token price (None if unavailable)
        no_price: Current NO token price (None if unavailable)
        complement_deviation: Absolute deviation from perfect complement (1.0)

    Examples:
        Complement arbitrage opportunity:

        >>> comp_signal = ComplementSignal(
        ...     market_slug="election-2024-candidate-wins",
        ...     yes_token_id="0x123abc456def...",
        ...     no_token_id="0x789ghi012jkl...",
        ...     yes_price=0.52,
        ...     no_price=0.43,
        ...     complement_deviation=0.05  # Prices sum to 0.95
        ... )
        >>> total = comp_signal.yes_price + comp_signal.no_price
        >>> print(f"Price sum: {total}, deviation: {comp_signal.complement_deviation}")
        Price sum: 0.95, deviation: 0.05

        Over-priced market (sum > 1.0):

        >>> overpriced = ComplementSignal(
        ...     market_slug="sports-championship-winner",
        ...     yes_token_id="0xabc123def456...",
        ...     no_token_id="0xdef789abc012...",
        ...     yes_price=0.58,
        ...     no_price=0.47,
        ...     complement_deviation=0.05  # Prices sum to 1.05
        ... )

    Trading Strategy:
        When complement_deviation > threshold:
        - If sum < 1.0: Buy both YES and NO tokens (guaranteed profit)
        - If sum > 1.0: Sell both YES and NO tokens (if positions exist)

        Expected profit = |deviation| * position_size - trading_fees

    Risk Considerations:
        - Market resolution risk if market is paused/cancelled
        - Liquidity risk if unable to exit positions
        - Fee impact on small deviations
        - Timing risk during high volatility periods

    """

    market_slug: str
    yes_token_id: str
    no_token_id: str
    yes_price: float | None
    no_price: float | None
    complement_deviation: float
