"""Initial schema

Revision ID: c2bb4752b603
Revises:
Create Date: 2025-08-24 15:04:04.031008

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2bb4752b603"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exposure_alerts", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "alert_type",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "outcome_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "threshold_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "current_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "triggered_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "acknowledged",
            existing_type=sa.BOOLEAN(),
            server_default="false",
            existing_nullable=True,
        )
        batch_op.drop_index("idx_exposure_alerts_type")
        batch_op.create_index(
            batch_op.f("ix_exposure_alerts_acknowledged"),
            ["acknowledged"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exposure_alerts_alert_type"), ["alert_type"], unique=False
        )

    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "bid",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ask",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "spread_bps",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "volume_24h",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "liquidity",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "snapshot_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_index("idx_market_snapshots_at")
        batch_op.create_index(
            batch_op.f("ix_market_snapshots_token_id"), ["token_id"], unique=False
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "side", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "size",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "filled_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.drop_index("idx_orders_created_at")
        batch_op.drop_index("idx_orders_market_slug")
        batch_op.drop_index("idx_orders_token_id")
        batch_op.create_index(
            batch_op.f("ix_orders_market_slug"), ["market_slug"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_orders_token_id"), ["token_id"], unique=False
        )

    with op.batch_alter_table("outcome_correlations", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "outcome_a",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_b",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "correlation",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=10, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "covariance",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "last_calculated",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_index("idx_outcome_correlations_outcomes")
        batch_op.create_unique_constraint(
            "_outcome_pair_uc", ["outcome_a", "outcome_b"]
        )

    with op.batch_alter_table("outcome_exposure_history", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "position_size",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "unrealized_pnl",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "risk_score",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=10, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "snapshot_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_index("idx_outcome_history_market")
        batch_op.drop_index("idx_outcome_history_snapshot")
        batch_op.create_index(
            batch_op.f("ix_outcome_exposure_history_snapshot_at"),
            ["snapshot_at"],
            unique=False,
        )

    with op.batch_alter_table("outcome_exposures", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_name",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "position_size",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "average_price",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "current_price",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "unrealized_pnl",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "realized_pnl",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "correlation_coefficient",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=10, scale=8),
            existing_nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )
        batch_op.alter_column(
            "risk_score",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=10, scale=8),
            existing_nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )
        batch_op.alter_column(
            "last_updated",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_index("idx_outcome_exposures_market")
        batch_op.drop_index("idx_outcome_exposures_outcome")
        batch_op.drop_index("idx_outcome_exposures_updated")
        batch_op.create_unique_constraint(
            "_market_outcome_uc", ["market_slug", "outcome_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_outcome_exposures_last_updated"),
            ["last_updated"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_outcome_exposures_market_slug"),
            ["market_slug"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_outcome_exposures_outcome_id"), ["outcome_id"], unique=False
        )

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.alter_column(
            "token_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "size",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.create_index(
            batch_op.f("ix_positions_market_slug"), ["market_slug"], unique=False
        )

    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "event_type",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "current_exposure",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "limit_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "intended_notional",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "occurred_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.create_index(
            batch_op.f("ix_risk_events_token_id"), ["token_id"], unique=False
        )

    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "order_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "side", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "size",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.REAL(),
            type_=sa.Numeric(precision=20, scale=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "executed_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_index("idx_trades_executed_at")
        batch_op.create_index(
            batch_op.f("ix_trades_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_trades_token_id"), ["token_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_token_id"))
        batch_op.drop_index(batch_op.f("ix_trades_order_id"))
        batch_op.create_index("idx_trades_executed_at", ["executed_at"], unique=False)
        batch_op.alter_column(
            "executed_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "size",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "side", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "order_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_events_token_id"))
        batch_op.alter_column(
            "occurred_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "intended_notional",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "limit_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "current_exposure",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "event_type",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_market_slug"))
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "size",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "token_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("outcome_exposures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outcome_exposures_outcome_id"))
        batch_op.drop_index(batch_op.f("ix_outcome_exposures_market_slug"))
        batch_op.drop_index(batch_op.f("ix_outcome_exposures_last_updated"))
        batch_op.drop_constraint("_market_outcome_uc", type_="unique")
        batch_op.create_index(
            "idx_outcome_exposures_updated", ["last_updated"], unique=False
        )
        batch_op.create_index(
            "idx_outcome_exposures_outcome", ["outcome_id"], unique=False
        )
        batch_op.create_index(
            "idx_outcome_exposures_market", ["market_slug"], unique=False
        )
        batch_op.alter_column(
            "last_updated",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "risk_score",
            existing_type=sa.Numeric(precision=10, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )
        batch_op.alter_column(
            "correlation_coefficient",
            existing_type=sa.Numeric(precision=10, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )
        batch_op.alter_column(
            "realized_pnl",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "unrealized_pnl",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "current_price",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "average_price",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "position_size",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("outcome_exposure_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outcome_exposure_history_snapshot_at"))
        batch_op.create_index(
            "idx_outcome_history_snapshot", ["snapshot_at"], unique=False
        )
        batch_op.create_index(
            "idx_outcome_history_market", ["market_slug", "outcome_id"], unique=False
        )
        batch_op.alter_column(
            "snapshot_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "risk_score",
            existing_type=sa.Numeric(precision=10, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "unrealized_pnl",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "position_size",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_name",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("outcome_correlations", schema=None) as batch_op:
        batch_op.drop_constraint("_outcome_pair_uc", type_="unique")
        batch_op.create_index(
            "idx_outcome_correlations_outcomes",
            ["outcome_a", "outcome_b"],
            unique=False,
        )
        batch_op.alter_column(
            "last_calculated",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "covariance",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "correlation",
            existing_type=sa.Numeric(precision=10, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_b",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "outcome_a",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_token_id"))
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index(batch_op.f("ix_orders_market_slug"))
        batch_op.create_index("idx_orders_token_id", ["token_id"], unique=False)
        batch_op.create_index("idx_orders_market_slug", ["market_slug"], unique=False)
        batch_op.create_index("idx_orders_created_at", ["created_at"], unique=False)
        batch_op.alter_column(
            "outcome_type",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "notional_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "filled_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "size",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "side", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_snapshots_token_id"))
        batch_op.create_index("idx_market_snapshots_at", ["snapshot_at"], unique=False)
        batch_op.alter_column(
            "snapshot_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "liquidity",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "volume_24h",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "spread_bps",
            existing_type=sa.Numeric(precision=10, scale=2),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ask",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "bid",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "token_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("exposure_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exposure_alerts_alert_type"))
        batch_op.drop_index(batch_op.f("ix_exposure_alerts_acknowledged"))
        batch_op.create_index(
            "idx_exposure_alerts_type", ["alert_type", "acknowledged"], unique=False
        )
        batch_op.alter_column(
            "acknowledged",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(FALSE)"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "triggered_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "current_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "threshold_value",
            existing_type=sa.Numeric(precision=20, scale=8),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "outcome_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "market_slug",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "alert_type",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    # ### end Alembic commands ###
